# this is an optional setup only to be  used if you have some pre-data that you want to insert before running the application  
#FROM postgres:latest

# replace the init.sql with any .sql backup 
# Example: COPY ./init.sql /docker-entrypoint-initdb.d/
# Example: RUN apt-get update && apt-get install -y postgresql-contrib

# Set environment variables (can also be set in docker-compose.yml)
#ENV POSTGRES_USER=myuser
#ENV POSTGRES_PASSWORD=mypassword
#ENV POSTGRES_DB=mydatabase

# Expose the PostgreSQL port
#EXPOSE 5432
